#!/usr/bin/env bash
# This script is displays numbers from 1 to 100 with FizzBuzz.
i=1
while [ "$i" -le 100 ]
do
    if [ $((i % 5)) -eq 0 ]
    then
		if [ $((i % 3)) -eq 0 ]
		then
			echo "FizzBuzz"
		else
			echo "Buzz"
		fi
    elif [ $((i % 3)) -eq 0 ]
    then
        echo "Fizz"
    else
        echo "$i"
    fi
	i=$((i + 1))
done
i=$i
