#!/usr/bin/env bash
# This script displays the visitor IP along with the HTTP status code from the Apache log file.
filename="apache-access.log"
awk -F' ' '{ print $1, $9}' $filename | sort | uniq -c| sort -nr
